### ISSUE TITLE
Publish self-hosted hidapi-rs

### ISSUE THREAD

**Issue by KaiseiYokoyama** [KaiseiYokoyama/joycon-rs#33]
Due to the effect of [hidapi's Issue], hidapi-rs can't open multiple JoyCons on macOS. So, I forked hidapi-rs and use it with [hidapi's Fork which fixes the bug]. I need to publish this [forked hidapi-rs] in crate.io.

[hidapi's Issue]: https://github.com/libusb/hidapi/issues/127
[hidapi's Fork which fixes the bug]: https://github.com/flirc/hidapi/tree/a4dd0f33ecae939cdad08c00934cac994cda3202
[hidapi's fork]: https://github.com/KaiseiYokoyama/hidapi-rs
[forked hidapi-rs]: https://github.com/KaiseiYokoyama/hidapi-rs

**Comment by KaiseiYokoyama** [comment]
hidapi-alt-for-hidapi-issue-127 = "1.2.1"

**Comment by KaiseiYokoyama** [comment]
https://crates.io/crates/hidapi-alt-for-hidapi-issue-127

🙏 `hidapi-rs` developpers 🙏

**Comment by carl-anders** [comment]
Just wanted to let you know that [hidapi 0.11](https://github.com/libusb/hidapi/releases/tag/hidapi-0.11.0) seems to have fixed this issue.

**hidapi-rs** has also been [updated](https://github.com/ruabmbua/hidapi-rs/commit/484eac8bd2e397ec5f067629633dfc4a94a507f7) to use this new hidapi 0.11.

**Comment by KaiseiYokoyama** [comment]
It's good news. I'll update the dependency immediately.
